version: '3.8'

services:
  # Identity mikroservisi için PostgreSQL veritabanı
  identity-postgres:
    image: postgres:16
    container_name: healthmonitoring-identity-postgres
    environment:
      POSTGRES_USER: healthmonitoring
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - identity-postgres-data:/var/lib/postgresql/data
    networks:
      - healthmonitoring-network

  # Organisation mikroservisi için PostgreSQL veritabanı
  organisation-postgres:
    image: postgres:16
    container_name: healthmonitoring-organisation-postgres
    environment:
      POSTGRES_USER: healthmonitoring
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: organisation
    ports:
      - "5433:5432"  # Farklı bir port kullanıyoruz, çünkü host üzerinde aynı portu birden fazla container kullanamaz
    volumes:
      - organisation-postgres-data:/var/lib/postgresql/data
    networks:
      - healthmonitoring-network

  # MongoDB veritabanı
  mongodb:
    image: mongo:7
    container_name: healthmonitoring-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: healthmonitoring
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
      MONGO_INITDB_DATABASE: healthmonitoring
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - healthmonitoring-network

  # RabbitMQ mesajlaşma sistemi
  rabbitmq:
    image: rabbitmq:3-management
    container_name: healthmonitoring-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: healthmonitoring
      RABBITMQ_DEFAULT_PASS: P@ssw0rd
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - healthmonitoring-network

networks:
  healthmonitoring-network:
    driver: bridge

volumes:
  identity-postgres-data:
  organisation-postgres-data:
  mongodb-data:
  rabbitmq-data: